### ISSUE TITLE
Some problems in Web Exploitation - Help Me Reset 2

### ISSUE THREAD

**Issue by bott0n** [PlatyPew/picoctf-2018-writeup#1]
I don't understand that how to find the answer in the reset question

Is this related to the username?

And I also find that if i go to [http://2018shell3.picoctf.com:26431/profile](http://2018shell3.picoctf.com:26431/profile) without login , I can still get the flag .

The Hint is "Try looking past the typical vulnerabilities. Think about possible programming mistakes."

Is the reset password is not the best way to get the flag?

Sorry for a junior player in ctf

**Comment by PlatyPew** [comment]
Sorry, but this challenge was solved by another team member. As such, I do not have much details on this.

From what I understand from your question, I'm assuming you are asking how the username is used to solve this challenge. You need a valid username to reset their password.

As for the `/profile` page, either it's a bug in the challenge, or it is indeed an intentional mistake. After all, it is quite common for developers to leave unused/testing files in the website.

Is resetting the password the best way to get the flag? It might be the intended solution, but this is a CTF. Any quick and dirty solutions that allow you to get the flag is valid, so long as it does not break the rules.

You might want to refer to https://s0cket7.com/picoctf-web/ for a better explanation on all the web challenges.

Hope this helped.

**Comment by bott0n** [comment]
Thanks a lot
